Fixed weird formatting bug in web page
mmurray22/my-portfolio pull request #32
Opened 2020-07-13 18:16 UTC by mmurray22

^^title

2020-07-13 19:05 UTC, ihsan314 approved these changes
LGTM

2020-07-14 00:10 UTC, ccondit requested changes
Can you be more specific about what the formatting bug was in the PR description? Maybe include a screenshot?

2020-07-14 00:24 UTC, mmurray22 commented
screenshots included!

2020-07-14 00:48 UTC, ccondit approved these changes
Nice! Thanks for the detail!

2020-07-15 01:38 UTC, kaveh096 approved these changes

2020-07-15 19:53 UTC, merged